'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { AppleSelect } from '@/components/ui/AppleSelect';
import { INDIAN_REGIONS, INDIAN_LANGUAGES, ACADEMIC_BRANCHES } from '@/lib/demographicData';
import { apiClient } from '@/lib/apiClient';

export default function ParticipantPortalPage() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);

  // Demographic registration form state matching v1 specification
  const [name, setName] = useState('');
  const [age, setAge] = useState('');
  const [gender, setGender] = useState('');
  const [branch, setBranch] = useState('');
  const [region, setRegion] = useState('');
  const [language, setLanguage] = useState('');

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || !age || !gender || !branch || !region || !language) {
      alert('Please fill out all demographic fields to register for the experimental study.');
      return;
    }

    setIsLoading(true);
    const demographics = {
      name: name.trim(),
      age: parseInt(age, 10),
      gender,
      branch,
      region,
      language,
      registered_at: new Date().toISOString(),
    };

    try {
      // Connect to backend/Supabase database to create participant and get generated ID
      const res = await apiClient.post<{ participant_code?: string; participant_id?: number }>(
        '/api/participant/register',
        { demographics }
      );

      const generatedCode = res.participant_code || (res.participant_id ? `P${res.participant_id.toString().padStart(6, '0')}` : null);
      
      if (generatedCode) {
        if (typeof window !== 'undefined') {
          localStorage.setItem(`aarrp_demographics_${generatedCode}`, JSON.stringify(demographics));
        }
        router.push(`/participant/${generatedCode}`);
        return;
      }
    } catch (error) {
      console.warn('Backend API connection fallback triggered. Generating client-side session ID.', error);
    }

    // Graceful fallback if standalone frontend on Vercel is temporarily disconnected from backend
    const fallbackCode = `P_${Math.floor(100000 + Math.random() * 900000)}`;
    if (typeof window !== 'undefined') {
      localStorage.setItem(`aarrp_demographics_${fallbackCode}`, JSON.stringify(demographics));
    }
    router.push(`/participant/${fallbackCode}`);
  };

  return (
    <main className="min-h-screen relative overflow-hidden flex flex-col items-center justify-center p-4 sm:p-6 bg-[#0b0f19] text-slate-100 py-12">
      {/* Ambient background glow */}
      <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-indigo-500/15 rounded-full blur-3xl pointer-events-none animate-pulse" />
      <div className="absolute bottom-10 left-10 w-80 h-80 bg-emerald-500/10 rounded-full blur-2xl pointer-events-none" />

      <div className="relative z-10 w-full max-w-xl space-y-6 animate-fade-in">
        <div className="text-center space-y-2">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-slate-400 hover:text-white transition-colors mb-2"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Portal Selection
          </Link>
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-white mt-2">
            Participant Registration
          </h1>
          <p className="text-sm text-slate-400 max-w-md mx-auto">
            Please enter your demographic details below. A unique research participant ID will be automatically generated by Supabase for anonymous tracking.
          </p>
        </div>

        <Card className="border-slate-800 bg-slate-900/90 backdrop-blur-xl shadow-2xl relative overflow-hidden p-6 sm:p-8 space-y-6">
          <div className="absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r from-orange-500 via-amber-500 to-yellow-500" />

          <form onSubmit={handleRegister} className="space-y-5 font-sans">
            {/* Full Name */}
            <div className="space-y-1.5">
              <label htmlFor="name" className="block text-xs font-bold text-slate-300 uppercase tracking-wider">
                Full Name <span className="text-rose-400">*</span>
              </label>
              <Input
                id="name"
                type="text"
                placeholder="e.g. Alex Johnson"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="bg-slate-950/80 border-slate-800 text-white placeholder:text-slate-600 focus:border-indigo-500 text-sm py-5 w-full rounded-xl"
                required
              />
            </div>

            {/* Age & Gender Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label htmlFor="age" className="block text-xs font-bold text-slate-300 uppercase tracking-wider">
                  Age <span className="text-rose-400">*</span>
                </label>
                <Input
                  id="age"
                  type="number"
                  min="15"
                  max="99"
                  placeholder="e.g. 20"
                  value={age}
                  onChange={(e) => setAge(e.target.value)}
                  className="bg-slate-950/80 border-slate-800 text-white placeholder:text-slate-600 focus:border-indigo-500 text-sm py-5 w-full rounded-xl"
                  required
                />
              </div>

              <AppleSelect
                label="Gender"
                value={gender}
                onChange={setGender}
                options={['Male', 'Female', 'Non-binary / Diverse', 'Prefer not to say']}
                placeholder="-- Select Gender --"
                required
              />
            </div>

            {/* Branch / Course */}
            <AppleSelect
              label="Branch / Major / Course"
              value={branch}
              onChange={setBranch}
              options={ACADEMIC_BRANCHES}
              placeholder="-- Select Branch / Course --"
              required
            />

            {/* Region / State */}
            <AppleSelect
              label="Region / State"
              value={region}
              onChange={setRegion}
              options={INDIAN_REGIONS}
              placeholder="-- Select Region / State --"
              required
            />

            {/* Primary Language */}
            <AppleSelect
              label="Primary Language (Mother Tongue)"
              value={language}
              onChange={setLanguage}
              options={INDIAN_LANGUAGES}
              placeholder="-- Select Language --"
              required
            />

            <div className="pt-4">
              <Button
                type="submit"
                variant="default"
                size="lg"
                disabled={isLoading}
                className="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-bold py-6 rounded-xl shadow-lg shadow-indigo-600/25 transition-all text-base"
              >
                {isLoading ? 'Connecting to Supabase Database...' : 'Start Reading Session →'}
              </Button>
            </div>
          </form>

          <div className="border-t border-slate-800/80 pt-4 flex items-center justify-between text-[11px] font-mono text-slate-500">
            <span>No User Auth Required</span>
            <span className="flex items-center gap-1.5 text-emerald-400 font-bold">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              Supabase Auto-ID Enabled
            </span>
          </div>
        </Card>
      </div>
    </main>
  );
}
