"""Initial schema

Revision ID: 709b5d97c4c7
Revises: 
Create Date: 2026-06-27 19:10:42.275171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709b5d97c4c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE IF NOT EXISTS participant_id_seq")
    op.create_table('administrator_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administrator_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_administrator_roles_name'))
    )
    op.create_index(op.f('ix_administrator_roles_id'), 'administrator_roles', ['id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['administrator_roles.id'], name=op.f('fk_administrators_role_id_administrator_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administrators'))
    )
    op.create_index(op.f('ix_administrators_email'), 'administrators', ['email'], unique=True)
    op.create_index(op.f('ix_administrators_id'), 'administrators', ['id'], unique=False)
    op.create_index(op.f('ix_administrators_username'), 'administrators', ['username'], unique=True)
    op.create_table('experiment_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_versions_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_versions'))
    )
    op.create_index(op.f('ix_experiment_versions_id'), 'experiment_versions', ['id'], unique=False)
    op.create_table('administrator_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['administrators.id'], name=op.f('fk_administrator_sessions_admin_id_administrators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administrator_sessions'))
    )
    op.create_index(op.f('ix_administrator_sessions_id'), 'administrator_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_administrator_sessions_token_hash'), 'administrator_sessions', ['token_hash'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['administrators.id'], name=op.f('fk_audit_logs_admin_id_administrators'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['experiment_versions.id'], name=op.f('fk_conditions_version_id_experiment_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conditions'))
    )
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.create_table('instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['experiment_versions.id'], name=op.f('fk_instructions_version_id_experiment_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instructions'))
    )
    op.create_index(op.f('ix_instructions_id'), 'instructions', ['id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.Column('user_prompt_template', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['experiment_versions.id'], name=op.f('fk_prompt_templates_version_id_experiment_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates'))
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_table('research_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=True),
    sa.Column('experiment_version_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrators.id'], name=op.f('fk_research_notes_administrator_id_administrators'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experiment_version_id'], ['experiment_versions.id'], name=op.f('fk_research_notes_experiment_version_id_experiment_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_notes'))
    )
    op.create_index(op.f('ix_research_notes_experiment_version_id'), 'research_notes', ['experiment_version_id'], unique=False)
    op.create_index(op.f('ix_research_notes_id'), 'research_notes', ['id'], unique=False)
    op.create_table('instruction_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instruction_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instruction_id'], ['instructions.id'], name=op.f('fk_instruction_images_instruction_id_instructions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruction_images'))
    )
    op.create_index(op.f('ix_instruction_images_id'), 'instruction_images', ['id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_code', sa.String(length=10), server_default=sa.text("'P' || lpad(nextval('participant_id_seq')::text, 6, '0')"), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], name=op.f('fk_participants_condition_id_conditions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['experiment_versions.id'], name=op.f('fk_participants_version_id_experiment_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants'))
    )
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_index(op.f('ix_participants_participant_code'), 'participants', ['participant_code'], unique=True)
    op.create_table('reading_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], name=op.f('fk_reading_texts_condition_id_conditions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_texts'))
    )
    op.create_index(op.f('ix_reading_texts_id'), 'reading_texts', ['id'], unique=False)
    op.create_table('paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_caption', sa.String(), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('is_intervention_trigger', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['reading_texts.id'], name=op.f('fk_paragraphs_text_id_reading_texts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paragraphs'))
    )
    op.create_index(op.f('ix_paragraphs_id'), 'paragraphs', ['id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['reading_texts.id'], name=op.f('fk_quiz_questions_text_id_reading_texts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions'))
    )
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_sessions_participant_id_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['experiment_versions.id'], name=op.f('fk_sessions_version_id_experiment_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_version_id'), 'sessions', ['version_id'], unique=False)
    op.create_table('ai_interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.Column('prompt_template_id', sa.Integer(), nullable=True),
    sa.Column('trigger_reason', sa.String(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraphs.id'], name=op.f('fk_ai_interventions_paragraph_id_paragraphs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], name=op.f('fk_ai_interventions_prompt_template_id_prompt_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_ai_interventions_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['experiment_versions.id'], name=op.f('fk_ai_interventions_version_id_experiment_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_interventions'))
    )
    op.create_index(op.f('ix_ai_interventions_id'), 'ai_interventions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_interventions_session_id'), 'ai_interventions', ['session_id'], unique=False)
    op.create_table('cursor_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('viewport_width', sa.Integer(), nullable=False),
    sa.Column('viewport_height', sa.Integer(), nullable=False),
    sa.Column('event_time_ms', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraphs.id'], name=op.f('fk_cursor_events_paragraph_id_paragraphs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_cursor_events_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['experiment_versions.id'], name=op.f('fk_cursor_events_version_id_experiment_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cursor_events'))
    )
    op.create_index(op.f('ix_cursor_events_id'), 'cursor_events', ['id'], unique=False)
    op.create_index(op.f('ix_cursor_events_session_id'), 'cursor_events', ['session_id'], unique=False)
    op.create_table('quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('option_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name=op.f('fk_quiz_options_question_id_quiz_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_options'))
    )
    op.create_index(op.f('ix_quiz_options_id'), 'quiz_options', ['id'], unique=False)
    op.create_table('reading_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('time_spent_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraphs.id'], name=op.f('fk_reading_events_paragraph_id_paragraphs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_reading_events_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['experiment_versions.id'], name=op.f('fk_reading_events_version_id_experiment_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_events'))
    )
    op.create_index(op.f('ix_reading_events_id'), 'reading_events', ['id'], unique=False)
    op.create_index(op.f('ix_reading_events_paragraph_id'), 'reading_events', ['paragraph_id'], unique=False)
    op.create_index(op.f('ix_reading_events_session_id'), 'reading_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_reading_events_version_id'), 'reading_events', ['version_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('optional_comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['ai_interventions.id'], name=op.f('fk_ai_feedback_intervention_id_ai_interventions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_ai_feedback_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['experiment_versions.id'], name=op.f('fk_ai_feedback_version_id_experiment_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_feedback')),
    sa.UniqueConstraint('intervention_id', name=op.f('uq_ai_feedback_intervention_id'))
    )
    op.create_index(op.f('ix_ai_feedback_id'), 'ai_feedback', ['id'], unique=False)
    op.create_table('quiz_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('likert_value', sa.Integer(), nullable=True),
    sa.Column('text_response', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name=op.f('fk_quiz_responses_question_id_quiz_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['quiz_options.id'], name=op.f('fk_quiz_responses_selected_option_id_quiz_options'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_quiz_responses_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['experiment_versions.id'], name=op.f('fk_quiz_responses_version_id_experiment_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_responses'))
    )
    op.create_index(op.f('ix_quiz_responses_id'), 'quiz_responses', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_responses_session_id'), 'quiz_responses', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SEQUENCE IF EXISTS participant_id_seq")
    op.drop_index(op.f('ix_quiz_responses_session_id'), table_name='quiz_responses')
    op.drop_index(op.f('ix_quiz_responses_id'), table_name='quiz_responses')
    op.drop_table('quiz_responses')
    op.drop_index(op.f('ix_ai_feedback_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_reading_events_version_id'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_session_id'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_paragraph_id'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_id'), table_name='reading_events')
    op.drop_table('reading_events')
    op.drop_index(op.f('ix_quiz_options_id'), table_name='quiz_options')
    op.drop_table('quiz_options')
    op.drop_index(op.f('ix_cursor_events_session_id'), table_name='cursor_events')
    op.drop_index(op.f('ix_cursor_events_id'), table_name='cursor_events')
    op.drop_table('cursor_events')
    op.drop_index(op.f('ix_ai_interventions_session_id'), table_name='ai_interventions')
    op.drop_index(op.f('ix_ai_interventions_id'), table_name='ai_interventions')
    op.drop_table('ai_interventions')
    op.drop_index(op.f('ix_sessions_version_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_paragraphs_id'), table_name='paragraphs')
    op.drop_table('paragraphs')
    op.drop_index(op.f('ix_reading_texts_id'), table_name='reading_texts')
    op.drop_table('reading_texts')
    op.drop_index(op.f('ix_participants_participant_code'), table_name='participants')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_instruction_images_id'), table_name='instruction_images')
    op.drop_table('instruction_images')
    op.drop_index(op.f('ix_research_notes_id'), table_name='research_notes')
    op.drop_index(op.f('ix_research_notes_experiment_version_id'), table_name='research_notes')
    op.drop_table('research_notes')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_instructions_id'), table_name='instructions')
    op.drop_table('instructions')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_administrator_sessions_token_hash'), table_name='administrator_sessions')
    op.drop_index(op.f('ix_administrator_sessions_id'), table_name='administrator_sessions')
    op.drop_table('administrator_sessions')
    op.drop_index(op.f('ix_experiment_versions_id'), table_name='experiment_versions')
    op.drop_table('experiment_versions')
    op.drop_index(op.f('ix_administrators_username'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_id'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_email'), table_name='administrators')
    op.drop_table('administrators')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_administrator_roles_id'), table_name='administrator_roles')
    op.drop_table('administrator_roles')
    # ### end Alembic commands ###
