export const INDIAN_REGIONS = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi (NCT)",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];

export const INDIAN_LANGUAGES = [
  "Assamese",
  "Bengali",
  "Bodo",
  "Dogri",
  "English",
  "Gujarati",
  "Hindi",
  "Kannada",
  "Kashmiri",
  "Konkani",
  "Maithili",
  "Malayalam",
  "Manipuri (Meitei)",
  "Marathi",
  "Nepali",
  "Odia",
  "Punjabi",
  "Sanskrit",
  "Santali",
  "Sindhi",
  "Tamil",
  "Telugu",
  "Urdu"
];

export const ACADEMIC_BRANCHES = [
  "B.Tech / B.E. - Aerospace Engineering",
  "B.Tech / B.E. - Artificial Intelligence & Data Science",
  "B.Tech / B.E. - Biotechnology",
  "B.Tech / B.E. - Chemical Engineering",
  "B.Tech / B.E. - Civil Engineering",
  "B.Tech / B.E. - Computer Science & Engineering (CSE)",
  "B.Tech / B.E. - Electrical & Electronics Engineering (EEE)",
  "B.Tech / B.E. - Electronics & Communication Engineering (ECE)",
  "B.Tech / B.E. - Information Technology (IT)",
  "B.Tech / B.E. - Mechanical Engineering",
  "B.Tech / B.E. - Robotics & Automation",
  "BCA (Bachelor of Computer Applications)",
  "MCA (Master of Computer Applications)",
  "M.Tech / M.E. - Computer Science / IT",
  "M.Tech / M.E. - Core Engineering Specialties",
  "B.Sc. - Computer Science / IT",
  "B.Sc. - Natural Sciences (Physics, Chem, Maths, Bio)",
  "M.Sc. - Sciences & Mathematics",
  "B.A. - Arts & Humanities (Psychology, Sociology, Lit)",
  "M.A. - Arts & Humanities",
  "BBA (Bachelor of Business Administration)",
  "MBA / PGDM (Master of Business Administration)",
  "B.Com / M.Com (Commerce & Accounting)",
  "MBBS / BDS / B.Pharm (Medical & Pharma)",
  "LLB / LLM (Law & Legal Studies)",
  "Ph.D. / Research Scholar"
];
